### ISSUE TITLE
Adding adjustment transaction

### ISSUE THREAD

**Issue by muhammadfarras** [muhammadfarras/Sistem-Komposisi-Dana#3]
### Menambahkan fitur untuk menambahakan transaski penyesuaian

Beberapa fiturnya
1. Menampilkan balance dari account adjustment ( apakah balance atau tidak)
2. Menyediakan formulir dinamik untuk menyeseuaikan jumalh transaksi yang dibutuhkan.
3. Membuat pilihan, transaksi penyesuaian tersebut apakah berasal dari sebuah transaksi atau penyesuaian yang tidak terikan dengan traksaksi, sehingga tampilkan transaksi yang sofId nya adalah Lainnya, serta pilihan yang tidak terikat dengan transaksi.
4. Setiap formulir dinamaik terisi, sebelum di catat kedalam data base tampilkan informasi apakah saldo sudah sesuai atau belum

**Comment by farras-sdit-anshal** [comment]
Closed, due to inactivate development
